### ISSUE TITLE
 No ['ROOT']['el'] element found in flex form definition

### ISSUE THREAD

**Issue by pececo** [franzholz/macina_searchbox#1]
"...Error in Backend while insert searchbox as conten-element..."
macina_search Data Structure ERROR: No ['ROOT']['el'] element found in flex form definition.
Actually i installed macina_searchbox 3.0.4 in Typo3 V8.7.32 preparing upgrades of Typo3 to v9.5.x

This could be the solution: 
in flexform_ds_pi1.xml
Wrong closing tag </s_special> in Line 33 ???
perhaps should be </s_general>

**Comment by franzholz** [comment]
Which version of TYPO3 is this?

**Comment by pececo** [comment]
as i described: 
Typo3 V8.7.32 and macina_searchbox 3.0.4

**Comment by pececo** [comment]
the error appears by adding searchbox as content-element in Plugin-Tab  instead of the select-field "display mode "

**Comment by franzholz** [comment]
Check this bugfix.

**Comment by pececo** [comment]
ok, tx, the error is fixed.
