### ISSUE TITLE
Installation problem on typo3-core 10.4

### ISSUE THREAD

**Issue by sergeyvo80** [franzholz/macina_searchbox#2]
trying to install a module on typo3 10.4 but getting the following error:

composer req jambagecom/macina-searchbox:3.0.5

Problem 1
    - Root composer.json requires jambagecom/macina-searchbox 3.0.5 -> satisfiable by jambagecom/macina-searchbox[v3.0.5].
    - jambagecom/macina-searchbox v3.0.5 requires typo3/cms-core 7.6,^8.7,^9.5,^10.4 -> found typo3/cms-core[dev-master, v8.7.7, ..., 8.7.x-dev, v9.0.0, ..., 9.5.x-dev, v10.0.0, ..., 10.4.x-dev, v11.0.0, ..., 11.5.x-dev (alias of dev-master)] but it does not match the constraint.

Installation from dev-master passes correctly
 composer req jambagecom/macina-searchbox:dev-master

**Comment by franzholz** [comment]
Retry it with the new version 3.0.6.
