### ISSUE TITLE
TYPO3 12 compatible version?

### ISSUE THREAD

**Issue by the-andyman** [franzholz/macina_searchbox#5]
Hello and many thanks for the great extension.

Is a version for TYPO3 12 planned or in development?

**Comment by franzholz** [comment]
When it is needed, then a new version could be built. 
Remind me of this again at the end of February 2024.

**Comment by w010** [comment]
How is it going with that? : )

**Comment by franzholz** [comment]
Please test the develop branch now and give me a feedback.

**Comment by the-andyman** [comment]
Sorry for the late response. 

I only got around to testing the new version (3.2.0) today. 

Unfortunately, it cannot be installed successfully (via the Extension Manager). After clicking on install, only “Access denied” is displayed. The backend can then no longer be accessed.

Tested with TYPO3 12.4.14 and PHP 8.2.x

Any ideas what the problem could be?

**Comment by franzholz** [comment]
Test the develop branch!

**Comment by the-andyman** [comment]
Thanks for the quick feedback and the fix. 
It seems to work now! 👍
